djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("restaurants/", include('truthtaste.urls', namespace='truthtaste')),
    path("users/", include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

truthtaste/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import delete_review

app_name = 'truthtaste'

urlpatterns = [
    path('list/', views.restaurant_list_list, name='all_restaurant_list'),
    path('<int:store_id>', views.restaurant_detail, name='restaurant-detail'),
    path('', views.home, name='home'),
    # path('auth/sign-up-page', views.signup_page, name='sign-up-page'),
    path('add-restaurant/', views.add_restaurant, name='add-restaurant'),
    path('edit-restaurant/<int:box_id>/', views.edit_restaurant, name='edit-restaurant'),
    path('delete-restaurant/<int:box_id>/', views.delete_restaurant, name='delete-restaurant'),
    path('create-review/', views.create_review, name='create-review'),
    path('delete-review/<int:review_id>/', delete_review, name='delete-review'),
    path('edit-review/<int:review_id>/', views.edit_review, name='edit-review'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('auth/log-in-page', views.login_page, name='log-in-page'),
    path('logout', views.logout, name='logout'),
]

truthtaste/models.py
from datetime import datetime
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

from djangoProject import settings


# Restaurant
class StoreBox(models.Model):
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='restaurant/')
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('truthtaste:restaurant-detail', args=[self.id])


# Reviews
class Review(models.Model):
    store = models.ForeignKey(StoreBox, on_delete=models.CASCADE, related_name='reviews')
    title = models.CharField(max_length=100)
    content = models.TextField()
    rating = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)


# class UserProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=100, blank=True)
#     last_name = models.CharField(max_length=100, blank=True)
#     email = models.EmailField(max_length=150)
#     newsletter_subscription = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.user.username

# class StoreBox:
#     def __init__(self, id, title, score, type, description, image):
#         self.id = id
#         self.title = title
#         self.score = score
#         self.type = type
#         self.description = description
#         self.image = image
#         # self.url = url


# box1 = StoreBox(
#     1,
#     "Riverside Roasters",
#     "4.5 (123)",
#     "Coffee shop",
#     "Freshly roasted beans paired with homemade desserts.",
#     "images/restaurant/restaurant-1.jpg"
# )
#
# box2 = StoreBox(
#     2,
#     "Sunrise Sips Café",
#     "4.3 (96)",
#     "Coffee shop",
#     "Rustic cafe offering organic blends & baked goods.",
#     "images/restaurant/restaurant-2.jpg"
# )
#
# box3 = StoreBox(
#     3,
#     "Daily Drip Coffeehouse",
#     "4.1 (215)",
#     "Coffee shop",
#     "Coffee oasis with an emphasis on sustainable practices.",
#     "images/restaurant/restaurant-3.jpg"
# )
#
# box4 = StoreBox(
#     4,
#     "Blue Cup Coffee",
#     "4.3 (96)",
#     "Coffee shop",
#     "Contemporary café serving both classic and experimental brews.",
#     "images/restaurant/restaurant-4.jpg"
# )
#
# box5 = StoreBox(
#     5,
#     "Leaf & Bean Lounge",
#     "4.5 (54)",
#     "Coffee shop",
#     "Every coffee bean tells a story of sustainability and care.",
#     "images/restaurant/restaurant-5.jpg"
# )
#
# box6 = StoreBox(
#     6,
#     "Blue Cup Coffee",
#     "4.5 (154)",
#     "Coffee shop",
#     "Embracing nature's serenity one brew at a time.",
#     "images/restaurant/restaurant-6.jpg"
# )
#
# box7 = StoreBox(
#     7,
#     "Twilight Espresso Longe",
#     "4.1 (133)",
#     "Coffee shop",
#     "Indulge in coffee as the city lights dim, a perfect blend of night and caffeine.",
#     "images/restaurant/restaurant-7.jpg"
# )
#
# box8 = StoreBox(
#     8,
#     "Canvas Coffee Gallery",
#     "4.4 (199)",
#     "Coffee shop",
#     "Where art and aroma create an enthralling masterpiece.",
#     "images/restaurant/restaurant-8.jpg"
# )
#
# store_boxes = []
# store_boxes.append(box1)
# store_boxes.append(box2)
# store_boxes.append(box3)
# store_boxes.append(box4)
# store_boxes.append(box5)
# store_boxes.append(box6)
# store_boxes.append(box7)
# store_boxes.append(box8)

regular_user = {"username": "Rick", "password": "regular"}
admin_user = {"username": "Emily", "password": "admin"}

truthtaste/views.py
from datetime import datetime

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import regular_user, admin_user, StoreBox, Review, User
from django.db.models import Avg, Value, FloatField
from django.db.models.functions import Coalesce
from actions.models import Action
from django.views.decorators.http import require_http_methods


def home(request):
    if request.session.get("username", False):  # Logged in
        # Feeds
        actions = Action.objects.all().order_by('-created')[:5]
        return render(request, "truthtaste/dashboard.html", {"actions": actions})
    else:
        return render(request, "truthtaste/home.html")


# List of all restaurant
def restaurant_list_list(request):
    sort_by = request.GET.get('sort_by', 'title_asc')

    # Use Coalesce to set the default average rating to 0 (If no ratings)
    store_boxes = StoreBox.objects.annotate(
        average_rating=Coalesce(Avg('reviews__rating'), Value(0), output_field=FloatField())
    )

    if sort_by == 'title_asc':
        store_boxes = store_boxes.order_by('title')
    elif sort_by == 'title_desc':
        store_boxes = store_boxes.order_by('-title')
    elif sort_by == 'score':
        store_boxes = store_boxes.order_by('-average_rating', 'title')
    else:
        store_boxes = store_boxes.order_by('type')

    actions = Action.objects.all().order_by('-created')[:5]
    context = {
        'store_boxes': store_boxes,
        "sort_by": sort_by,
        "actions": actions
    }

    return render(request,
                  "truthtaste/restaurant_list/restaurant-list.html", context)


# Detail of the restaurant
def restaurant_detail(request, store_id):
    store = get_object_or_404(StoreBox, id=store_id)
    reviews = store.reviews.all().order_by('-date')

    # Calculate the average rating if there are reviews
    average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    if average_rating is not None:
        average_rating = round(average_rating, 1)

    actions = Action.objects.all().order_by('-created')[:5]
    context = {
        'store': store,
        'reviews': reviews,
        'average_rating': average_rating,
        "actions": actions
    }
    return render(request, 'truthtaste/restaurant_list/restaurant-detail.html', context)


# For adding a new restaurant
def add_restaurant(request):
    if not request.session.get("username", False):
        messages.error(request, 'Only login users can add restaurants')
        return redirect('truthtaste:home')

    if request.method == 'POST':
        title = request.POST.get('add-title')
        type = request.POST.get('add-type')
        description = request.POST.get('add-description')
        image = request.FILES.get('add-image', None)

        user = User.objects.get(username=request.session.get("username"))

        ns = StoreBox(
            title=title,
            type=type,
            description=description,
            # author=user
            author=request.session['username']
        )
        if image:
            ns.image = image
        ns.save()

        # Log the action
        action = Action(
            user=user,
            verb="created the restaurant",
            target=ns,
        )
        action.save()

        messages.success(request, "You have successfully added the restaurant: %s." % ns.title,
                         extra_tags='success-add')
        # Redirect to the detail view for the new item
        return redirect('truthtaste:restaurant-detail', store_id=ns.id)
    else:
        return render(request, 'truthtaste/add-restaurant.html')


# For editing a restaurant
def edit_restaurant(request, box_id):
    # Check if user is logged in
    if not request.session.get("username"):
        messages.error(request, 'Only login users can edit the restaurant.')
        return redirect('truthtaste:home')
    try:
        box = StoreBox.objects.get(id=box_id)
    except StoreBox.DoesNotExist:
        messages.error(request, 'The restaurant does not exist!')
        return redirect('truthtaste:all_restaurant_list')

    if request.method == 'POST':
        user = User.objects.get(username=request.session.get("username"))
        title = request.POST.get('add-title')
        type = request.POST.get('add-type')
        description = request.POST.get('add-description')
        image = request.FILES.get('add-image', None)

        if title and title != box.title:
            box.title = title
            action = Action(
                user=user,
                verb="edited the restaurant title",
                target=box,
            )
            action.save()

        if description and description != box.description:
            box.description = description
            action = Action(
                user=user,
                verb="edited the restaurant description",
                target=box,
            )
            action.save()

        if type:
            box.type = type
        if image:
            box.image = image

        box.save()
        messages.success(request, "The restaurant %s was edited successfully!" % box.title, extra_tags='success-edit')
        return redirect('truthtaste:restaurant-detail', store_id=box.id)

    context = {
        'box': box,
    }
    return render(request, 'truthtaste/edit-restaurant.html', context)


# For deleting a restaurant
def delete_restaurant(request, box_id):
    user = get_object_or_404(User, username=request.session.get("username"))
    try:
        box = StoreBox.objects.get(id=box_id)
        box_title_deleted = box.title

        action = Action(
            user=user,
            verb="deleted a restaurant",
            details=f": {box_title_deleted}"
        )
        action.save()
        box.delete()
        messages.success(request, 'The restaurant %s was deleted successfully!' % box.title,
                         extra_tags='success-delete')
    except StoreBox.DoesNotExist:
        messages.error(request, 'The restaurant does not exist.')
    return redirect('truthtaste:all_restaurant_list')


def signup_page(request):
    messages.error(request, 'The registration feature is still in the development stage.')
    return render(request, "truthtaste/auth/sign-up-page.html")


def create_review(request):
    print("create_review")
    # print(request.body)
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == "POST":
        try:
            store_id = int(request.POST.get('store_id'))
            title = request.POST.get('title')
            content = request.POST.get('content')
            rating = request.POST.get('rating')
            author = request.session.get('username')
            date = datetime.now()

            review = Review(
                store=StoreBox.objects.get(id=store_id),
                date=date,
                title=title,
                content=content,
                rating=rating,
                author=author,
            )
            print(review)
            review.save()

            can_edit = (author == request.session.get('username')) or request.user.is_superuser

            messages.success(request, "Your review was created successfully!")
            return JsonResponse(
                {'success': 'success', 'message': 'Successfully added a new review.', 'title': title, 'rating': rating
                    , 'content': content, 'author': author, 'can_edit': can_edit,
                 'review_id': review.id
                 }, status=200)
            # return redirect('truthtaste:restaurant-detail', store_id=store.id)
        except Review.DoesNotExist:
            return JsonResponse({'error': 'No store found for this ID'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)


# @require_http_methods(["DELETE"])
def delete_review(request, review_id):
    print("Delete review request received")
    review = get_object_or_404(Review, id=review_id)

    if review.author == request.session.get('username') or request.session.get('role') == 'admin':
        review.delete()
        messages.success(request, 'Review successfully deleted.')
        return redirect('truthtaste:restaurant-detail', store_id=review.store.id)
    else:
        messages.error(request, 'Permission denied')
        return redirect('truthtaste:restaurant-detail', review_id=review.store.id)


def edit_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)

    if review.author != request.session.get('username') and request.session.get('role') != 'admin':
        messages.error(request, 'You do not have permission to edit reviews.')
        return redirect('truthtaste:restaurant-detail', store_id=review.store.id)

    if request.method == 'POST':
        review.title = request.POST.get('title')
        review.content = request.POST.get('content')
        review.rating = request.POST.get('rating')
        review.save()

        messages.success(request, 'Reviews successfully edited!')
        return redirect('truthtaste:restaurant-detail', store_id=review.store.id)
    else:
        return render(request, 'truthtaste/edit-review.html', {'review': review})

templates/truthtaste/add-restaurant.html
{% extends "truthtaste/base.html" %}
{% load static %}
{% block page-title %}Restaurant info{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/review-form.css' %}"/>
{% endblock %}


{% block main-content %}

    <div class="create-review-page">

        <form method="post" action="{% url 'truthtaste:add-restaurant' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Create a restaurant</h1>
            <p> (* = required)</p><br>

            <div>
                <label class="review-section-label">Restaurant Name<span class="required">*</span></label>
                <input class="input-box" placeholder="" type="text" name="add-title" required>
            </div>

            <div>
                <label class="review-section-label">Type<span class="required">*</span></label>
                <input class="input-box" placeholder="" type="text" name="add-type" required>
            </div>

            <div>
                <label class="review-section-label">Description</label>
                <textarea class="input-box" name="add-description"></textarea>
            </div>

            <div>
                <label class="review-section-label">Upload Image<span class="required">*</span></label>
                <input type="file" name="add-image" required>
            </div><br>

            <button type="submit" id="submit-btn">Submit</button>
        </form>
    </div>
{% endblock %}

templates/truthtaste/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>TruthTaste NoVA | {% block page-title %}{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta name="description" content="List of restaurants"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" type="text/css" href="{% static "css/global.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/app.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/app-header.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/app-footer.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/restaurant-list.css" %}"/>
{#    <script src={% static "js/jquery-3.7.1.min.js" %}></script>#}
    <script src={% static "js/jquery-3.7.1.min.js" %}></script>
    <script src={% static "js/script.js" %}></script>
    {% block extra-css %}{% endblock %}


{#    <script src="static/js/script.js"></script>#}
</head>

<body>
<!-- HEADER -->
<header class="header-container">
    <a href="{% url 'truthtaste:home' %}" class="logo-container">
        <img id="logo" src="{% static "images/site/TruthTaste-logo-only.png" %}" alt="Logo"/>
        <h1 id="title">TruthTaste<br/>NoVA</h1>
    </a>

    <!-- Search Bar -->
    <div class="search-bar-section">
        <form action="search-result.html" class="search-box">
            <input type="text" class="search-bar" placeholder="Search Restaurant by Location, Name, or Type"/>
            <button type="submit" class="search-button">
                <img
                        src="{% static "images/site/search.svg" %}"
                        alt="Search"
                />
            </button>
        </form>
    </div>

    <!-- Icons -->
    {% if request.session.username %}
        <div class="nav-icons">
            <a href="{% url 'truthtaste:all_restaurant_list' %}" class="nav-button">
                <img src="{% static "images/site/list.svg" %}" alt="List Button"/>
                <span class="nav-button-label">List</span>
            </a>

            <a href="{% url 'users:profile' request.session.username %}" class="nav-button">
                <img src="{% static "images/site/user.svg" %}" alt="User Button"/>
                <span class="nav-button-label">{{ request.session.username }}</span></a
            >

            <a href="{% url 'users:logout' %}" class="nav-button">
                <img src="{% static "images/site/logout.svg" %}" alt="Logout Button"/>
                <span class="nav-button-label">Log out</span>
            </a>
        </div>

    {% else %}
        <div class="nav-icons">
            <a href="{% url 'users:log-in-page' %}" class="nav-button">
                <img src="{% static "images/site/login.svg" %}" alt="Login Button"/>
                <span class="nav-button-label">Log In</span>
            </a>
        </div>

    {% endif %}


</header>

<main>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- Main Content -->
    {% block main-content %}{% endblock %}
</main>

<!-- FOOTER -->
<footer class="footer-container">
    <section class="links">
        <a href="{% url 'truthtaste:home' %}">Home</a>
        <p>｜</p>
        <a href="index.html">About</a>
        <p>｜</p>
        <a href="index.html">Directions</a>
        <p>｜</p>
        <a href="index.html">Contact</a>
    </section>
    <section class="copyright">
        <p>Copyright © 2023 TruthTaste NoVA. All Rights Reserved.</p>
    </section>
</footer>
</body>
</html>

templates/truthtaste/create-review-page.html
{% extends "truthtaste/base.html" %}
{% load static %}
{% block page-title %}Restaurant info{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/review-form.css' %}"/>
{% endblock %}

{% block main-content %}

    <div class="create-review-page">
        <h1>Restaurant: {{ store.title }}</h1>
        <h2>Review Form</h2>

        <form method="post" enctype="multipart/form-data" class="review-form"
              action="{% url 'truthtaste:create_review' store.id %}">

            {% csrf_token %}
            <label for="title" class="review-section-label">Title <span class="required">*</span></label>
            <input type="text" id="title" name="title" class="input-box" required>

            <label for="content" class="review-section-label">Write a Review <span class="required">*</span></label>
            <textarea id="content" name="content" class="input-box" required></textarea>

            <label for="rating" class="review-section-label">Overall Rating <span class="required">*</span></label>

            <div class="stars">
                <input type="radio" id="star5" name="rating" value="5"/><label for="star5">&#9733;</label>
                <input type="radio" id="star4" name="rating" value="4"/><label for="star4">&#9733;</label>
                <input type="radio" id="star3" name="rating" value="3"/><label for="star3">&#9733;</label>
                <input type="radio" id="star2" name="rating" value="2"/><label for="star2">&#9733;</label>
                <input type="radio" id="star1" name="rating" value="1"/><label for="star1">&#9733;</label>
            </div>

            <button type="submit" id="submit-btn">Submit</button>
        </form>
    </div>
{% endblock %}

templates/truthtaste/dashboard.html
{% extends "truthtaste/base.html" %}
{% load static %}
{% block page-title %}Home Page{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block main-content %}
    <div class="home-page">
        <div class="welcome-text">
            <h1>Discover NoVA's Best Dining</h1>
        </div>

        <section class="search-wrapper">
                <div class="search-desc">
                    <p>Welcome Back, {{ request.session.username }}!</p>
                    <p class="personalized-desc">
                        Continue exploring amazing food in Northern Virginia. Try new flavors, talk about your great meals, and discover more about food.
                    </p>
                    <a href="{% url 'truthtaste:all_restaurant_list' %}" class="cta-btn">Continue Browsing</a>
                </div>
        </section>
    </div>
    {% include "actions/action/feed.html" %}
{% endblock %}

templates/truthtaste/delete-restaurant.html
{#{% extends "truthtaste/base.html" %}#}
{##}
{#{% block content %}#}
{#<div class="container">#}
{#    <h2>Confirm Delete</h2>#}
{#    <p>Are you sure you want to delete the restaurant "{{ box.title }}"?</p>#}
{##}
{#    <form method="post" action="{% url 'truthtaste:delete_restaurant' box.id %}">#}
{#        {% csrf_token %}#}
{#        <input type="submit" value="Confirm Delete" class="btn btn-danger">#}
{#    </form>#}
{##}
{#    <a href="{% url 'truthtaste:restaurant-detail' box.id %}" class="btn btn-secondary">Cancel</a>#}
{#</div>#}
{#{% endblock %}#}

templates/truthtaste/edit-restaurant.html
{% extends "truthtaste/base.html" %}
{% load static %}
{% block page-title %}Restaurant info{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/review-form.css' %}"/>
{% endblock %}

{% block main-content %}

    <div class="create-review-page">

        <form method="post" action="{% url 'truthtaste:edit-restaurant' box.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Edit Restaurant</h1>

            <div>
                <label class="review-section-label">Restaurant Name<span class="required">*</span></label>
                <input class="input-box" value="{{ box.title }}" type="text" name="add-title" required>
            </div>

            <div>
                <label class="review-section-label">Type<span class="required">*</span></label>
                <input class="input-box" value="{{ box.type }}" type="text" name="add-type" required>
            </div>

            <div>
                <label class="review-section-label">Description</label>
                <textarea class="input-box" name="add-description">{{ box.description }}</textarea>
            </div>

            <div>
                <label class="review-section-label">Current Image</label><br>
                <img src="{{ box.image.url }}" alt="{{ box.title }}" style="width: 200px; height: auto;"><br><br>
                <label class="review-section-label">Upload New Image</label>
                <input type="file" name="add-image">
            </div><br>

            <button type="submit" id="submit-btn">Update</button>
        </form>
    </div>
{% endblock %}

templates/truthtaste/edit-review.html
{% extends 'truthtaste/base.html' %}

{% block main-content %}
    <div class="container">
        <h2>Edit Review</h2>


        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post" action="{% url 'truthtaste:edit-review' review.id %}">
            {% csrf_token %}

            <label for="title">Title:</label>
            <input type="text" id="title" name="title" value="{{ review.title }}" required>

            <label for="rating">Rating:</label>
            <select id="rating" name="rating" required>
                <option value="1" {% if review.rating == 1 %}selected{% endif %}>1</option>
                <option value="2" {% if review.rating == 2 %}selected{% endif %}>2</option>
                <option value="3" {% if review.rating == 3 %}selected{% endif %}>3</option>
                <option value="4" {% if review.rating == 4 %}selected{% endif %}>4</option>
                <option value="5" {% if review.rating == 5 %}selected{% endif %}>5</option>
            </select>

            <label for="content">Content:</label>
            <textarea id="content" name="content" required>{{ review.content }}</textarea>

            <button type="submit" class="submit-btn">Update Review</button>
        </form>
    </div>
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#<div class="container">#}
{#    <h2>Edit Reviews</h2>#}
{#    <form method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        <label for="title">Title</label>#}
{#        <input type="text" id="title" name="title" value="{{ review.title }}" required>#}
{##}
{#        <label for="rating">Rating</label>#}
{#        <input type="number" id="rating" name="rating" value="{{ review.rating }}" min="1" max="5" required>#}
{##}
{#        <label for="content">Content</label>#}
{#        <textarea id="content" name="content" required>{{ review.content }}</textarea>#}
{##}
{#        <button type="submit" class="btn">Update</button>#}
{#    </form>#}
{#</div>#}
{% endblock %}

templates/truthtaste/home.html
{% extends "truthtaste/base.html" %}
{% load static %}
{% block page-title %}Home Page{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block main-content %}
    <div class="home-page">
        <div class="welcome-text">
            <h1>Discover NoVA's Best Dining</h1>
        </div>

        <section class="search-wrapper">
            <p class="search-desc">
                Dive into reviews of the most applauded restaurants in Northern Virginia.<br>
                Join us now to share your gourmet experiences!
            </p>
            <a href="{% url 'users:register' %}" class="auth-button">Create an Account</a>
            or
            <a href="{% url 'users:log-in-page' %}" class="auth-button">Log In</a>
            or
            <a href="{% url 'truthtaste:all_restaurant_list' %}" class="cta-btn">Start Browsing as a Guest</a>

        </section>
    </div>
    {% include "actions/action/feed.html" %}
{% endblock %}